# Configuration file for https://console.cloud.google.com/cloud-build
# https://console.cloud.google.com/home/dashboard?project=jflex-ci
steps:
- id: "build_and_test_all"
  name: 'gcr.io/cloud-marketplace-containers/google/bazel:3.5.0'
  entrypoint: 'bash'
  args: ['scripts/google-cloud.build.sh']
